### ISSUE TITLE
Implement a CountDownTimer

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#1]
Create a `CountDownTimer` ⏲ for a fixed 5 second period. 
The timer kicks off as soon as the app starts - _without any physical interaction_.

### Should
- tick every 1 second. ⏲ 
- print a `Log.v` statement indicating the seconds remaining.
- print a `Log.v` statement when the countdown finishes

### Should not
- have audible ticks. _Not required at this point._ 🔇 
- reflect any chages in UI. 📵 

### Special Note
- In order to gauge interest and being the first issue on this project, everyone is invited to create their own countdowntimer and raise a **Pull Request**.
- Although, this isn't much code, but make sure you follow best coding practices & conventions,  and comment wherever necessary.
- This issue will remain _open_ for an extended period so all those who are interested can raise a PR over the weekend.
- Please do mention your `@Slack id.abnd` username.

Happy Coding 👍

**Comment by piedcipher** [comment]
I would like to work on this issue.

My Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Hey @piedcipher, 
Welcome aboard! Glad to have you here. Since this issue is open for all, it won't be specifically assigned. But please start working on it and when you are done, raise a PR.
