### ISSUE TITLE
Spinners in SettingsActivity

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#10]
Must be started after #8 is closed.
**Requires 3 spinners:**
```
Work duration:
____________________
25 minutes      \/ |
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```
### Spinner 1
**Title:** Work duration:
**Values:** 20 minutes , 25 minutes (default) , 30 minutes , 40 minutes , 55 minutes

### Spinner 2
**Title:** Short break duration:
**Values:** 3 minutes , 5 minutes (default) , 10 minutes , 15 minutes

### Spinner 3
**Title:** Long break duration:
**Values:** 10 minutes , 15 minutes (default) , 20 minutes , 25 minutes

_Note: Please store all `Strings` in strings.xml._

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by codersanjeev** [comment]
I would like to work on this issue.

**Comment by numerative** [comment]
Please go ahead! 👍
