### ISSUE TITLE
Make spinners store values to SharedPreferences

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#11]
Must start after #10 is solved.

### Expected Behaviour
Selecting options from the dropdown should set a corresponding value to SharedPreferences.
e.g. Choosing 25 minutes from spinner should set a value `150000` (miliseconds) to SharedPreferences.

This problem hasn't been figured out end-to-end and will require some experimenting on your end - but here's a supporting SO [link](https://stackoverflow.com/questions/5068115/spinner-selection-save-to-sharedpreferences-then-retrieve).

Please include `Log.v(` statements for easy testing purposes.

If you hit a dead-end, comment back here with the problem and we'll solve this together.... 

Please declare all miliseconds as a final constant.
e.g.  `private final long TWENTY_FIVE_MINUTES = 150000;`

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by codersanjeev** [comment]
I am working on this issue @numerative

**Comment by numerative** [comment]
Noted! 👍

**Comment by codersanjeev** [comment]
There is no need to declare these duration variables as the array in spinners is always the same. So, just storing the position in shared preferences would work. @numerative
