### ISSUE TITLE
Use Butterknife library for View Binding

### ISSUE THREAD

**Issue by codersanjeev** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#13]
Use Butterknife library for View Binding

### Steps to reproduce
Add the dependencies and replace all findViewById() methods with Butterknife

### Expected behaviour
A lot of boilerplate code will be reduced

### Actual behaviour
Many lines of code are used in View Binding which can be reduced easily using this library

### Would you like to work on the issue?
Yes

**Comment by numerative** [comment]
Agreed. Butterknife would reduce a lot of boilerplate code. :smiley:

Please proceed with this and push changes so that your PR solve #10 and #13 at the same time. 
Since I don't have access to PC now, I'll merge the changes in the morning.
