### ISSUE TITLE
App fails to start on an android 8.1 device (API 27)

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#17]
App fails to start with a `Pomodoro - get more done, faster has stopped` error message on two Android 8.1 devices. Of the two, one is a physical device, whereas the other is an AVD.

### Steps to reproduce
Running the application on an 8.1 device. Should be reporducable on any 8.0+ devices.

Here is the log error:
```
Failed to start service from exception: 
    java.lang.IllegalStateException: Not allowed to start service Intent { act=org.chromium.components.sync.notifier.ACTION_REGISTER_TYPES cmp=com.android.chrome/org.chromium.chrome.browser.invalidation.ChromeInvalidationClientService (has extras) }: app is in background uid UidRecord{8521f30 u0a71 CEM  idle change:cached procs:1 seq(0,0,0)}
```

Running git bisect points to commit `058ae0dbc2c14eab7393f1afe7bdd8868eacc9db` as the first bad commit.

cc: @kartikohri1712 

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by amCap1712** [comment]
I have fixed it. Please check. @numerative
