### ISSUE TITLE
Java Logic for countdown_textview_main

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#19]
Required Java Logic to display `millisUntilFinished` on the main activity's `countdown_textview_main`. 

Here's a supporting SO link to achieve the same. --> https://stackoverflow.com/a/41589025/8411356

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by savanipoojan78** [comment]
I am interested @Poojan_Savani.abnd

**Comment by numerative** [comment]
Great! 😄 👍

**Comment by numerative** [comment]
Hey @savanipoojan78, 
I just hope you are still interested in taking up this issue. Asking because I noticed you still haven't forked the repo.

**Comment by savanipoojan78** [comment]
I Have made a PR look at that

**Comment by numerative** [comment]
Hey Poojan,
I have some feedback which I'll share tomorrow when I have access to my PC. It seems you've misunderstood the issue.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`
