### ISSUE TITLE
Multiple instances of activity open on clicking Service notification.

### ISSUE THREAD

**Issue by amCap1712** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#20]
Multiple instances of activity open on clicking Foreground Service notification. 

### Steps to reproduce
Click the Pomodoro App notification multiple times while it is running. At this moment, the service is only started on starting the app. For better understanding, increase the `TIME_PERIOD` of the counter in `MainActivity` to prolong the duration of notification. Multiple instance are evident when back button is pressed.

### Expected behaviour
Ideally, a single instance of activity should be open. If no instance is in memory, a new one should be created but if it is memory, it should be reopened instead of creating a new activity.

### Actual behaviour
Every time the notification is clicked a new instance of the activity is created.

**Comment by numerative** [comment]
@kartikohri1712 
For now, the serviceIntent has been moved to the Start/Stop button. 
This issue can still be reproduced if that button is hit multiple times, but it will be solved when the work / break cycle logic is implemented (issue for which is currently being written)

**Comment by numerative** [comment]
Moreover, in my opinion will not be wise to interfere with activity lifecycle for this matter. Please let me know if you think otherwise.
