### ISSUE TITLE
Java Logic for Work / Break Cycles

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#21]
_This is the core functionality of the app._ 
### Required
There are 2 kinds of breaks in the pomodoro technique, 1. _Short_ and 2. _Long_.
At the end of each _complete_ work session the user starts a _short_ break with a button click. Except, at the _completion_ of every 4th work session the user takes _long_ break. 

Each of the work duration, short break duration, and long break duration values are taken from the respective spinner selection made in SettingsActivity. (Values are stored as SharedPreferences)

### Expected Behaviour
1. A single Toggle Button handles all states.

2. Each _completed_ session is counted and at the end of every _completed_ work session the user is allowed to either start a short or long break. _Counts to be maintained as shared preferences._

3. Cancelled Work sessions should not be counted.

4. Clicking `COMPLETE` button counts towards number of _completed_ sessions.

While the toggle button only has two states: checked and unchecked, the single `timer_button_main`, will serve to fulfill all states. The following table indicates the **button tap behaviour**:

| Serial | unchecked | checked | re-unchecked
|-------|----------|---------|--------
| 1. | Start Pomodoro | Cancel Pomdoro | 1. |
| 2. | Start Short Break | Cancel Short Break  | 1. |
| 3. | Start Long Break | Cancel Long Break | 1. |

Note: Whenever any state is cancelled, the next state is always `Start Pomodoro`. i.e. 

> This is a challenging issue and may be broken down into several smaller issues. 
> Instead of taking up the whole issue as a whole, take up a small part of it and comment below on what you will be working on (a corresponding issue will be created after your comment). Better still, create an issue and reference that issue from the comments below.
>Comments on this issue should be used to coordinate joint effort.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Please go ahead.
