### ISSUE TITLE
Toggle Button functionality to Start / Cancel Timer

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#22]
Currently the Toggle button's code is placed incorrectly placed in the onClick method of the MainActivity.

### Required
1. Toggle Button's unchecked state should run the timer and (while the timer is still running) the checked state should cancel the running timer.
2. Once the timer finishes (`onFinish`) reset the toggle button to the unchecked state so that the timer can be started again.

> This issue is in pursuance of #21 
-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by codersanjeev** [comment]
I am working on this issue @numerative
