### ISSUE TITLE
Counting number of Work Sessions completed

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#23]
Every successfully completed work session must be counted towards completed work sessions. This counter will eventually help choose between long break and short break.

### Required
1. Store the counter value as a shared preference and whenever the countDownTimer's `onFinish` method is called, the counter value should increase by 1.
2. For testing purposes, reflect the value of the counter in MainActivity's `session_completed_value_textview_main`.

> This issue is in pursuance of #21 

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Assigned
