### ISSUE TITLE
COMPLETE button logic

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#24]
### Required
When the COMPLETE button is clicked, the work session timer stops and the session is counted towards completed.

Reason behind this feature: The aim of the Pomdoro technique is to finish a task at hand faster. So, if a user has completed a task, it is a valid reason to finish that session and go take a break earlier and not wait for the timer.

### Expected Behaviour
1. COMPLETE buttons stops the timer.
2. Resets Toggle button to checked state so that the user can take a break.

> Must start after #23 is resolved

> This issue is in pursuance of #21 

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Cool! Assigned.
