### ISSUE TITLE
Design Material Launcher Icon

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#25]
Design adaptive icons as per the current material guidelines found here.

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by geekykant** [comment]
Hey, I am @geekykant. 
Can I give it a try?

**Comment by ghost** [comment]
I am interested

**Comment by numerative** [comment]
Hi @geekykant and @ @iamhshaikh,

Glad to see your participation here.

Both of you may work on this project. It is better to have choices for design elements.

However, only one icon will be merged with the project, in the end.

Please do follow the material guidelines while designing.
