### ISSUE TITLE
Replace COMPLETE and SETTINGS button labels to Images

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#27]
Currently the COMPLETE and SETTINGS button contain a text label. In order to reduce the size of the buttons and make the UI look cleaner replace the text with the following image labels:

| Text | Image |
|----|------|
| COMPLETE | ✔️ |
| SETTINGS | ⚙️ |

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by codersanjeev** [comment]
go ahead @piedcipher

**Comment by numerative** [comment]
Super duper! 👍🏼
