### ISSUE TITLE
Create a simple MainActivity Layout

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#3]
The aim of this issue is to have a UI elements, like TextView and Buttons, whereby we can interact with our app and get feedback. Do note, this is a very basic UI requirement - no material guidelines, no special formatting. Just clean and simple.

Following elements are required:
 ### Required
- One TextView for the countdown display. You may include placeholder like `25:00`.
- Three Buttons at the bottom of the screen arranged in a row.
  - Left Button: to complete a task prematurely.
  - Center Button: Toggle button to Start/Stop Timer.
  - Right Button: to navigate to settings screen
- Use of ConstraintLayout.

### Not Required
- Formatting.
- Java logic.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by codersanjeev** [comment]
I would like to work on this issue.
My slack ID - @sanjeev.abnd

**Comment by numerative** [comment]
Awesome! Please proceed with this.

Good Luck! 👍🏼
