### ISSUE TITLE
START / CANCEL button doesn't reset to START at the end of timer

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#30]
Toggle button doesn't change state at the end of the timer so as to restart the timer.

### Steps to reproduce
Wait till the timer ticks down to zero.

### Expected behaviour
Button state should change to START

### Actual behaviour
The button stays on the CANCEL state.

cc: @thedevelopersanjeev

**Comment by codersanjeev** [comment]
Working on this issue.

**Comment by numerative** [comment]
Great!
