### ISSUE TITLE
Create an Alert Dialog with 3 buttons - XML ONLY

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#38]
Create a xml layout for alert dialog with a **title** and **3 buttons**. 

This layout will be used as a prompt at the end of every work session to start a short or long break.

**REQUIRED:**

1. The title and buttons are center aligned and appear in this order from top to bottom
    1. TITLE
    1. LARGE BUTTON
    1. Medium Button
    1. small  or text-only low-importance button. (used for 'Cancel')

Java code isn't required for this task, just the xml file.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Great! Please start working on it.
