### ISSUE TITLE
Java Logic for Alert Dialog

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#39]
**Expected Behaviour:**

- Popups at the end of every work session.
- The title congratulates user on completing the work session.
- LARGE button prompts user to start short or long break (depending on the `currentlyRunningServiceType`).
- Medium button offers user to start alternative break short or long, which are out of turn. e.g. this button lets user start a long break even though it is turn for a short break.
- small button let's user Cancel the break. The button closes the alert dialog and resets the `timer_button_main`  to 'START POMODORO' state.

> Starts after #38 

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Awesome! Please start working on this. 😀
