### ISSUE TITLE
Design Layout Mockups for the App (2 screens)

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#41]
The app's working, but that's just it. A well-polished UI is a must if you want your user to love your app. Our app needs UI polish and the first step towards it would be preparing mockups.
Below is the current screen shot of our app.

![pomodoro_screen_1](https://user-images.githubusercontent.com/28054527/48408222-cef67300-e75e-11e8-8f81-5d210ee7db62.png) ![pomodoro_screen_2](https://user-images.githubusercontent.com/28054527/48408224-cef67300-e75e-11e8-9a7f-7f139063ca0c.png)

**REQUIRED:**
1. Mockups of the above two screens. 
2. Mockups must adhere to material guidelines. (e.g. choice of colours, padding, font sizes, etc.)

_Be imaginative, but be grounded... After all it needs to be coded too, right?_

Good Luck!

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest along with your `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by ghost** [comment]
Any  feedback @numerative @piedcipher @s3rius @Deepamgoel @geekykant 
Most Welcome..

![start_activity](https://user-images.githubusercontent.com/42109980/48721891-cd3e1b00-ec48-11e8-98fe-c99a59e9d2ce.jpg)
![stop_activity](https://user-images.githubusercontent.com/42109980/48721893-cdd6b180-ec48-11e8-9518-c1497a4799f4.jpg)

**Comment by piedcipher** [comment]
Great Job @iamhshaikh Looks amazing :sparkles: :+1:

**Comment by geekykant** [comment]
Its amazing man! I love it.

**Comment by numerative** [comment]
This looks great @iamhshaikh, thanks!

I have a couple of changes based on the [roadmap 2.0 ](https://github.com/google-udacity-india-scholars/abnd-track-pomodoro-timer-app/wiki) changes. 

- Labels _Change Task, shuffle icon, and work session completed_ are not required.
- Instead of displaying number _2_, it should display two check marks, e.g. ✔️ ✔️ .

**Comment by ghost** [comment]
@numerative can you share some sketches??

**Comment by numerative** [comment]
Here you go. Just as simple as this. 

![](https://i.imgur.com/iXjDe7B.png)

**Comment by ghost** [comment]
Means no text and change button only Checkbox

**Comment by numerative** [comment]
True.
The whole card will become clickable, so no need for a separate button.

**Comment by ghost** [comment]
Ohh I understood I will be back with some wireframing sketches

**Comment by ghost** [comment]
I have created one


![mainscreen](https://user-images.githubusercontent.com/42109980/48982612-e3e1e780-f10a-11e8-88ac-cc0a58b990fb.jpg)

**Comment by ghost** [comment]
Also just small icon hope you will like it 

![ic_launcher](https://user-images.githubusercontent.com/42109980/48982628-1db2ee00-f10b-11e8-9212-73de5f5e2689.png)

**Comment by codersanjeev** [comment]
awesome work @iamhshaikh
