### ISSUE TITLE
Sliding Transition between MainActivity and SettingsActivity

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#46]
Use right to left **slide animation** to transition between MainActivity and SettingsActivity.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by amy6** [comment]
I'd like to work on this issue.

**Comment by numerative** [comment]
🎉 🎊
Awesome! You may start working on this issue.
