### ISSUE TITLE
Display Notification when service ends

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#47]
Notify users to start next session / break when the timer stops.

Based on the `currentlyRunningServiceType` values, user should be notified to start that it is time for either:
1. Break over. Resume work.
2. Time for a Short Break.
3. Time for a Long Break.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by piedcipher** [comment]
I would like to work on this issue.
Slack ID - `@tirth.abnd`

**Comment by numerative** [comment]
Great! Please start working on it.
