### ISSUE TITLE
Do not display Heads up notification when starting timer

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#48]
Whenever the timer is started, heads up notification is displayed. This is an unexpected behaviour.
![untitled](https://user-images.githubusercontent.com/28054527/48551664-2ed65080-e8fc-11e8-8ebd-453d7235992c.png)

### Steps to reproduce
Start the timer.

### Expected behaviour
Heads up notification shouldn't be displayed.

> The issue is because the notification channel importance is set to `IMPORTANCE_HIGH` which should be set to `IMPORTANCE_LOW`.
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by s3rius** [comment]
I'll try to fix it.

**Comment by codersanjeev** [comment]
go ahead @s3rius
