### ISSUE TITLE
App as a background service while it is running

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#5]
In order to prevent the app from stopping while the timer is running, make the countdown timer run as a service.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by amCap1712** [comment]
I want to work on this task.

**Comment by numerative** [comment]
Awesome!
Please start working on it. 😃

**Comment by numerative** [comment]
@kartikohri1712, I just came across this video and it looks like what we need is a foreground service.

https://youtu.be/FbpD5RZtbCc

Background service might not just work.

**Comment by numerative** [comment]
Hi @kartikohri1712, 
Not to rush you or anything, but can you please just provide an update on the work?
Thanks!

**Comment by amCap1712** [comment]
Almost done. Hoping to submit a PR by tonight.

**Comment by numerative** [comment]
Thanks for the update and that's good to know. 😃
