### ISSUE TITLE
Notification Action Buttons: When Pomodoro Session is Running. 1/4

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#60]
### Required:
Service notification which allows users to do undertake following tasks _when_  the pomodoro session is running:

✔ Complete  |  ❌ Dismiss

> This issue is in pursuance of #59 

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by hasanmohdkhan** [comment]
I am interested in this issue

**Comment by numerative** [comment]
Great. You may start working on this issue. 👍🏼
