### ISSUE TITLE
Notification Action Buttons: When Pomodoro Session is Complete. 2/4

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#61]
### Required:
Notification which allows users to do undertake following task _when_  the pomodoro session is complete:

▶ Start Short/Long Break 

> This issue is in pursuance of #59   

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by hasanmohdkhan** [comment]
I interested in this issue

**Comment by numerative** [comment]
Hey @hasanmohdkhan,
I am currently modifying the previous changes so that the buttons work even without opening the activity. So, once that is fixed, we can implement similar changes to remaining 3 issues.

**Comment by hasanmohdkhan** [comment]
ok, I will wait then, I have changes ready in my local repo.
