### ISSUE TITLE
alert dialog layout messed up

### ISSUE THREAD

**Issue by bharatmk2567** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#69]
an alert dialog layout looks weird.

### Steps to reproduce
just change the layout code. 

### Expected behavior
all button and texts are on the left side

### Actual behavior
buttons and text should be at the center of the dialog view 

### Would you like to work on the issue?
yes I can work on it I have already changed the code in my repo

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In the case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
Can you please describe the issue? Is it a bug or you wish to redesign the layout of alert dialog?

**Comment by bharatmk2567** [comment]
i am sharing link of photo
[https://photos.app.goo.gl/mTKqdMmm4bAECqmo7](url)

**Comment by numerative** [comment]
I see. Any idea why this is happening? Shows up correctly on my device.

**Comment by bharatmk2567** [comment]
I have seen inside "layout_alert_dialog.xml" file there is used linear layout inside constraint layout
so for a different device it will show different

**Comment by numerative** [comment]
Okay.
I see you have already made changes. Please create a PR then.

**Comment by bharatmk2567** [comment]
okay
