### ISSUE TITLE
Layout Change - Add a Card between timer TextView and row of Buttons

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#7]
Make changes to the current MainActivity Layout so that there is a Card between the timer TextView and Row of Buttons.
Here is a relevant link for the purpose. https://material.io/develop/android/components/material-card-view/

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by Deepamgoel** [comment]
What is the card intended for?

**Comment by numerative** [comment]
It is to display the current task the user is working on and the number of work sessions the user has completed on that task.

**Comment by Deepamgoel** [comment]
I'd like to work on this.
Slack Username: Deepam Goel.abnd

**Comment by numerative** [comment]
Awesome! 😁
Please start working on it.
