### ISSUE TITLE
Create a new SettingsActivity which opens from the Settings Button

### ISSUE THREAD

**Issue by numerative** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#8]
Just an empty activity which opens when the Settings Button is clicked.
No layout changes required required.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by codersanjeev** [comment]
I am interested.

**Comment by numerative** [comment]
Cool! Please start working.
